version: '3'

services:
    
    mosquitto:
        image: eclipse-mosquitto:1.6.15
        ports:
          - "1883:1883"
        #volumes:
        #  - mosquitto-data:/mosquitto/data
        #  - mosquitto-logs:/mosquitto/logs
        #  - mosquitto-conf:/mosquitto/config
        domainname: aerosimmqtt
        restart: unless-stopped

#volumes:
#    mosquitto-data:
#    mosquitto-logs:
#    mosquitto-conf:

